name: (E2E Tests) Meshery Adapter for Linkerd Tests

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
    paths-ignore:
      - 'docs/**'   
  pull_request:
     branches:
       - "*"
  release:
    types: [published]

jobs:
  SetPatternfile:
    runs-on: ubuntu-latest
    outputs:
      sm_version: ${{ steps.glrt.outputs.release }}
      adapter_version:  ${{ env.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Get latest release tag
        id: gettag
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: linkerd/linkerd2
          excludes: prerelease, draft, edge 
      - name: Get stable release version
        id: getstabletag
        run: |
          if [ ${{ github.event_name }} == "release" ]; then
            stable_release=${GITHUB_REF/refs\/tags\//}
            echo "stable_release=$stable_release" >> $GITHUB_ENV
          else
            stable_release=$(curl -sL "https://linkerd.io/releases/" | grep -oP 'Stable \(latest version: \K[^)]+' | head -n1)
            echo "stable_release=$stable_release" >> $GITHUB_ENV
          fi

      - name: Change service mesh version in patternfile
        run: | 
           yq e -i '.services.linkerd.version="${{ env.stable_release }}"' ./.github/install/deploy.yaml 
           cat ./.github/install/deploy.yaml
      - name: Uploading file
        uses: actions/upload-artifact@v3
        with:
          name: patternfile
          path: ./.github/install/deploy.yaml 

  TestLinkerd:
    needs: SetPatternfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master

      - name: Download patternfile
        uses: actions/download-artifact@v2
        with:
          name: patternfile
          path: ./.github/install

      - name: Setup Meshery CLI
        run: |
          curl -L https://github.com/meshery/meshery/releases/download/v0.7.25/mesheryctl_0.7.25_Linux_x86_64.tar.gz | tar xz
          sudo mv mesheryctl /usr/local/bin/
          mesheryctl version


      - name: Run Meshery Adapter Tests
        run: |
          mesheryctl mesh validate --file ./.github/install/deploy.yaml

      - name: Save test results
        run: |
          echo '{ "test_result": "success" }' > data.json

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: data.json
          path: data.json

  UpdateDocs:
    needs: TestLinkerd
    if:  "always() && github.event_name != 'pull_request' "
    runs-on: ubuntu-latest
    steps:
      - name: Skip if needed
        run: |
            echo "this is it ${{ needs.SkipIfNeeded.outputs.skipdocupdate }} "
            if [ "${{github.event_name }}" == "push" ];then
              echo "version=edge" >> $GITHUB_ENV
            fi
            if [ "${{github.event_name }}" == "release" ];then
              echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
            fi
      - uses: actions/checkout@master
        with:
          repository: meshery/meshery 
          token: ${{ secrets.GH_ACCESS_TOKEN }}   
      - name: DownloadJSON
        uses: actions/download-artifact@v3
        with:
          name: data.json
      - name: echo results
        run: |
          pretty=$(jq . data.json)
          rm data.json
          mkdir -p ./docs/_compatibility/meshery-linkerd
          cd ./docs/_compatibility/meshery-linkerd
          touch data.json
          echo $pretty > data.json
          cat data.json
          touch test.md
          filename=(`date +%m-%d-%Y-%H-%M-%m_${SHORT_SHA}`)
          echo $filename
          echo "---
          timestamp: $(jq '.metadata.runon| strptime("%a %b %e %X %Z %Y") | strftime("%Y-%m-%d %X %Z %a")' data.json)
          meshery-component: meshery-linkerd
          meshery-component-version: $version
          meshery-server-version: $(jq '.metadata."meshery-server-version"' data.json)
          k8s-distro: minikube
          k8s-version: $(jq '.metadata.k8s_version' data.json)
          service-mesh: Linkerd
          service-mesh-version: $(jq '.metadata.service_mesh_version' data.json)
          tests:
            pod/linkerd-destination: $(jq '.resources_status."pod/linkerd-destination"' data.json)
            pod/linkerd-identity: $(jq '.resources_status."pod/linkerd-identity"' data.json)
            pod/linkerd-proxy-injector:  $(jq '.resources_status."pod/linkerd-proxy-injector"' data.json)
          overall-status: $(jq '."overall-status"' data.json)
          ---" >  test.md
          mv test.md $filename.md
          rm data.json
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: docs
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
          commit_message: '[Docs] Test status of adapter'
