name: (E2E Tests) Meshery Adapter for Linkerd Tests

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
    paths-ignore:
      - 'docs/**'   
  pull_request:
     branches:
       - "*"
  release:
    types: [published]
jobs:
  SetPatternfile:
    runs-on: ubuntu-latest
    outputs:
      sm_version: ${{ steps.glrt.outputs.release }}
      adapter_version:  ${{ env.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Get latest release tag
        id: gettag
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: linkerd/linkerd2
          excludes: prerelease, draft, edge 
      - name: Get stable release version
        id: getstabletag
        run: |
          if [ ${{ github.event_name }} == "release" ]; then
            stable_release=${GITHUB_REF/refs\/tags\//}
            echo "stable_release=$stable_release" >> $GITHUB_ENV
          else
            stable_release=$(curl -sL "https://linkerd.io/releases/" | grep -oP 'Stable \(latest version: \K[^)]+' | head -n1)
            echo "stable_release=$stable_release" >> $GITHUB_ENV
          fi

      # - name: Get latest release tag
      #   id: gettag
      #   uses: pozetroninc/github-action-get-latest-release@master
      #   with:
      #     repository: 
      #     excludes: prerelease, draft, edge 

      - name: Change service mesh version in patternfile
        run: | 
           yq e -i '.services.linkerd.version="${{ env.stable_release }}"' ./.github/install/deploy.yaml 
           cat ./.github/install/deploy.yaml
      - name: Uploading file
        uses: actions/upload-artifact@v3
        with:
          name: patternfile
          path: ./.github/install/deploy.yaml 
